node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('2921f39f-b090-4e37-9ce2-5486052fbac1', 'dockerhub') {
       def app = docker.build("navneetaswani/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
